### PR TITLE
JPMS support

### LINKED ISSUE #19: Add module-info.java to support JPMS
#### Describe the feature

The `vertx-launcher-application` jar should contain a `module-info.class` file, making it a named / explicit module. 

#### Use cases

As part of the Vert.x 5.0 release Vert.x tries to support the Java Module System, see [What's new in Vert.x 5, Java Modules](https://vertx.io/blog/whats-new-in-vert-x-5/#java-modules).
By providing a `module-info.java` the VertxApplication class would be usable as a launcher with `jlink`. Building a runtime image with `jlink` is only supported with named / explicit modules.

##### Example without `VertxApplication`

By starting the module through a main method in the client code itself it's currently possible to use `jlink`.

```java
public class MainVerticle extends VerticleBase {

	public static void main(String[] args) {
		Vertx vertx = Vertx.vertx();
		vertx.deployVerticle(new MainVerticle())
			.onFailure(Throwable::printStackTrace);
	}

  @Override
  public Future<?> start() {
    return vertx.createHttpServer().requestHandler(req -> {
      req.response()
        .putHeader("content-type", "text/plain")
        .end("Hello from Vert.x!");
    }).listen(8888).onSuccess(http -> {
      System.out.println("HTTP server started on port 8888");
    });
  }
}
```

```java
module com.example.module_example {
	requires io.vertx.core;
}
```

```kotlin
val launcherModule = "com.example.module_example"
val launcherClassName = "com.example.module_example.MainVerticle"

application {
  mainModule.set(launcherModule)
  mainClass.set(launcherClassName)
}

tasks.register<JavaExec>("jlink") {
	group = "build"

    mainClass.set("jdk.tools.jlink.internal.Main")
    mainModule.set("jdk.jlink")

    var modulePath = files()
    modulePath.from(configurations.runtimeClasspath)
    modulePath.from(tasks.jar)
    println(modulePath.joinToString(":"))
    args = listOf(
            "--module-path",
            modulePath.joinToString(":"),
            "--add-modules",
            "java.base,java.compiler,java.logging,java.naming,jdk.unsupported,${application.mainModule.get()}",
            "--output",
            "build/jlink-image-test",
            "--launcher",
            "launch=${application.mainModule.get()}/${application.mainClass.get()}"
    )
}
```

##### Currently not working

```java
public class MainVerticle extends VerticleBase {

  @Override
  public Future<?> start() {
    return vertx.createHttpServer().requestHandler(req -> {
      req.response()
        .putHeader("content-type", "text/plain")
        .end("Hello from Vert.x!");
    }).listen(8888).onSuccess(http -> {
      System.out.println("HTTP server started on port 8888");
    });
  }
}
```

```java
module com.example.module_example {
	requires io.vertx.core;

	exports com.example.module_example to vertx.launcher.application, io.vertx.core;
}
```

```kotlin
val launcherModule = "vertx.launcher.application"
val launcherClassName = "io.vertx.launcher.application.VertxApplication"

application {
  mainModule.set(launcherModule)
  mainClass.set(launcherClassName)
}

tasks.register<JavaExec>("jlink") {
	group = "build"

    mainClass.set("jdk.tools.jlink.internal.Main")
    mainModule.set("jdk.jlink")

    var modulePath = files()
    modulePath.from(configurations.runtimeClasspath)
    modulePath.from(tasks.jar)
    println(modulePath.joinToString(":"))
    args = listOf(
            "--module-path",
            modulePath.joinToString(":"),
            "--add-modules",
            "java.base,java.compiler,java.logging,java.naming,jdk.unsupported,${application.mainModule.get()}",
            "--output",
            "build/jlink-image-test",
            "--launcher",
            "launch=${application.mainModule.get()}/${application.mainClass.get()}"
    )
}
```

#### Contribution

Who should implement this feature ? are you volunteering for implementing this feature or
do you know that is able and willing implement this feature ?

I think this would do the trick:

```java
module vertx.application.launcher {
	requires io.vertx.core;
	requires io.vertx.core.logging;
	requires io.vertx.docgen;

	requires info.picocli;
}
```

But the launcher needs one more package that `vertx.core` currently [doesn't export to it](https://github.com/eclipse-vertx/vert.x/blob/3d281cb2b05c26c209111e32478c93639183f0ed/vertx-core/src/main/java/module-info.java#L98):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project vertx-launcher-application: Compilation failure
[ERROR] vertx-launcher/application/src/main/java/io/vertx/launcher/application/impl/VertxApplicationCommand.java:[16,21] package io.vertx.core.impl is not visible
[ERROR]   (package io.vertx.core.impl is declared in module io.vertx.core, which does not export it to module vertx.application.launcher)
```

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #19

### CODE REVIEW

File: application/src/main/java/module-info.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+module io.vertx.launcher.application {
+  requires info.picocli;
+  requires io.vertx.core;
+  requires io.vertx.core.logging;
+
+  // Annotation processing
+  requires static io.vertx.docgen;
+
+  uses io.vertx.core.spi.VertxServiceProvider;
+  opens io.vertx.launcher.application.impl to info.picocli;
```
Comment (vietj) [inline application/src/main/java/module-info.java:21]: interesting

Comment (tsegismont) [reply application/src/main/java/module-info.java:21]: This is required for Picocli to access the fields annotated in our command implementation.
